// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lZm-rLxfSVyNTmCsbxhpZeW95U0hW5c',
    appId: '1:804719664181:web:c7baa990919ccccd63657c',
    messagingSenderId: '804719664181',
    projectId: 'ngl2024',
    authDomain: 'ngl2024.firebaseapp.com',
    databaseURL: 'https://ngl2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ngl2024.firebasestorage.app',
    measurementId: 'G-G3HVTQG8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Iqr3uSuQnP1UVQHdxgp377DQvCAfsfU',
    appId: '1:804719664181:android:b3b6178b6410a17063657c',
    messagingSenderId: '804719664181',
    projectId: 'ngl2024',
    databaseURL: 'https://ngl2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ngl2024.firebasestorage.app',
  );

}